// Code generated by goctl. DO NOT EDIT!
// Source: demo.proto

package server

import (
	"context"

	"go-zero-demo/app/demo/cmd/rpc/internal/logic"
	"go-zero-demo/app/demo/cmd/rpc/internal/svc"
	"go-zero-demo/app/demo/cmd/rpc/pb"
)

type DemoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDemoServer
}

func NewDemoServer(svcCtx *svc.ServiceContext) *DemoServer {
	return &DemoServer{
		svcCtx: svcCtx,
	}
}

func (s *DemoServer) List(ctx context.Context, in *pb.ListReq) (*pb.ListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *DemoServer) Add(ctx context.Context, in *pb.AddReq) (*pb.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *DemoServer) Updata(ctx context.Context, in *pb.UpdateReq) (*pb.UpdateResp, error) {
	l := logic.NewUpdataLogic(ctx, s.svcCtx)
	return l.Updata(in)
}

func (s *DemoServer) Del(ctx context.Context, in *pb.DelReq) (*pb.DelResp, error) {
	l := logic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}
