// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	testFieldNames          = builder.RawFieldNames(&Test{})
	testRows                = strings.Join(testFieldNames, ",")
	testRowsExpectAutoSet   = strings.Join(stringx.Remove(testFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	testRowsWithPlaceHolder = strings.Join(stringx.Remove(testFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheLooklookUsercenterTestIdPrefix = "cache:looklookUsercenter:test:id:"
)

type (
	testModel interface {
		Insert(ctx context.Context, data *Test) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Test, error)
		Update(ctx context.Context, data *Test) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTestModel struct {
		sqlc.CachedConn
		table string
	}

	Test struct {
		Id       int64  `db:"id"`
		Mobile   string `db:"mobile"`
		Nickname string `db:"nickname"`
	}
)

func newTestModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTestModel {
	return &defaultTestModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`test`",
	}
}

func (m *defaultTestModel) Delete(ctx context.Context, id int64) error {
	looklookUsercenterTestIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterTestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, looklookUsercenterTestIdKey)
	return err
}

func (m *defaultTestModel) FindOne(ctx context.Context, id int64) (*Test, error) {
	looklookUsercenterTestIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterTestIdPrefix, id)
	var resp Test
	err := m.QueryRowCtx(ctx, &resp, looklookUsercenterTestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", testRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTestModel) Insert(ctx context.Context, data *Test) (sql.Result, error) {
	looklookUsercenterTestIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterTestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, testRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Mobile, data.Nickname)
	}, looklookUsercenterTestIdKey)
	return ret, err
}

func (m *defaultTestModel) Update(ctx context.Context, data *Test) error {
	looklookUsercenterTestIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterTestIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, testRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Mobile, data.Nickname, data.Id)
	}, looklookUsercenterTestIdKey)
	return err
}

func (m *defaultTestModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheLooklookUsercenterTestIdPrefix, primary)
}

func (m *defaultTestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", testRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTestModel) tableName() string {
	return m.table
}
