// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	test "go-zero-demo/app/demo/cmd/api/internal/handler/test"
	"go-zero-demo/app/demo/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test/list",
				Handler: test.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/test/add",
				Handler: test.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/test/updata",
				Handler: test.UpdataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/test/delete",
				Handler: test.DelHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo/v1"),
	)
}
