// Code generated by goctl. DO NOT EDIT.
package types

type Test struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type ListReq struct {
	Mobile   string `json:"mobile,optional"`
	Nickname string `json:"nickname,optional"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
}

type ListResp struct {
	TestInfo   []Test `json:"testInfo"`
	TotalCount int64  `json:"totalCount"`
}

type AddReq struct {
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type AddResp struct {
	TestInfo Test `json:"testInfo"`
}

type UpdateReq struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type UpdateResp struct {
	TestInfo Test `json:"testInfo"`
}

type DelReq struct {
	Id int64 `json:"id"`
}

type DelResp struct {
	Msg string `json:"msg"`
}
